project: 
  type: website
  output-dir: docs
  
execute: 
  freeze: auto
  
website:
  favicon: favicon.png
  page-navigation: true
  title: "Cary's Personal Workspace" 
  site-url: "https://carypersonal.github.io/cary-personal-workspace/" 
  repo-url: https://github.com/CaryPersonal/cary-personal-workspace.git 
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Cary, 2023"
    
  sidebar:
    logo: "images/workspace.jpg"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://carypersonal.github.io/cary-personal-workspace/
        text: "Cary's Personal Workspace"
      - icon: github
        href: https://github.com/CaryPersonal
        text: "Cary's GitHub Profile"
      - icon: twitter
        href: https://twitter.com/Cary_Huang_
        text: "Cary's Twitter"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - href: Tools-and-Tips.qmd
        text: Tools and Tips
      - section: UCL-Schoolwork/index.qmd
        text: UCL Schoolwork
        contents:
          - href: UCL-Schoolwork/STAT0011.qmd
            text: STAT0011
          - href: UCL-Schoolwork/STAT0023.qmd
            text: STAT0023
          - href: UCL-Schoolwork/STAT0024.qmd
            text: STAT0024
          - href: UCL-Schoolwork/ECON0047.qmd
            text: ECON0047
          - href: UCL-Schoolwork/MATH0050.qmd
            text: MATH0050
      - href: learning-more.qmd
        text: Learn more
      - href: transition-from-rmarkdown.qmd
        text: Transition from Rmd


format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto